Classes:
    #NameOfClass:
        #Perks:
        #- Feed
        #Kit:
          #- WOOD 2
          #- LOG 3
    Kronos:
        Perks:
          - Time
          - Playertime
          - Weather
          - Back
        Kit:
          - WATCH 1
          - COMPASS 1
          - IRON_SWORD 1
          - GOLD_HELMET 1
          - IRON_CHESTPLATE 1
          - GOLD_LEGGINGS 1
          - IRON_BOOTS 1
    Hephaestus:
        Perks:
          - Anvil
          - Craft
          - Ignite
          - Grenade
        Kit:
          - ANVIL 3
          - IRON_PICKAXE 1
          - IRON_AXE 1
          - IRON_SPADE 1
          - DIAMOND_HELMET 1
          - IRON_CHESTPLATE 1
          - IRON_LEGGINGS 1
          - DIAMOND_BOOTS 1
          - FLINT_AND_STEEL 1
          - OBSIDIAN 2
          - TORCH 64
          - IRON_FENCE 32
          - IRON_INGOT 16
          - GOLD_INGOT 8
          - COAL 32
          - IRON_BLOCK 1
    Artemis:
        Perks:
          - 
        Kit:
          - BOW 1
          - DIAMOND_SWORD 1
          - ARROWS 128
          - ENDER_PEARL 5
          - CHAINMAIL_BOOTS 1
          - CHAINMAIL_LEGGINGS 1
          - CHAINMAIL_CHESTPLATE 1
          - CHAINMAIL_HELMET 1
    # placeholder for next class
