name: MythsOfCreation
version: 1.0
main: me.NerfFlamer.Main
description: Adds an rpg aspect to the game
author: ckm499, NerfFlamer
commands:
    nyxpoints:
        description: Access the Nyx Shop and view your Nyx Point balance
        aliases: np
    class:
        description: Join and leave classes and view class info
        aliases: c
    ckit:
        description: Get class kit
    invis:
        description: Make yourself invisible for a certain time
    fury:
        description: Core perk for Ares
    sheild:
        description: Core perk for Hephaestus
    sprint:
        description: Core perk for Kronos
    regen:
        description: Core perk for Artemis