name: NyxPoints
version: 1.0
main: me.NerfFlamer.Main
description: Adds an rpg aspect to the game
author: ckm499, NerfFlamer
commands:
    nyxpoints:
        description: Access shop and view your Nyx Point balance
        aliases: np